### ISSUE TITLE
Resolve unknown custom type URLs in `urlResolver`

### ISSUE THREAD

**Issue by vabatta** [somethingnew-co/prismic#11]
The `urlResolver` makes the implcit assumption that a route object is specified for a given custom type, but this could not be always true. 
Specifically, https://github.com/somethingnew-co/prismic/blob/v1.2.4/packages/prismic/src/urlResolver.ts#L30 can be `undefined` and thus the default route `'/'` should be returned instead.

**Comment by bitmap** [comment]
Thanks for the feedback, this is resolved in `v1.2.5`
