### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by vabatta** [somethingnew-co/prismic#8]
Hi,

can you update the packages with the new versions of each peer dependency? They are all retro-compatible: `"next@^9.5 || next@^10.0", "react@^16.8 || react@^17.0", "react-dom@^16.8 || react-dom@^17.0"`.

**Comment by bitmap** [comment]
👋 peerDependencies have been updated in version `1.2.4`

thanks for bringing this to our attention.
